### ISSUE TITLE
Icons misalignment

### ISSUE THREAD

**Issue by fynks** [LeeVD/plasma-applet-net-bandwidth-monitor#18]
Icons aren't aligned perfectly in release ```0.3.2``` even after tinkering with layout padding method.
Text gets aligned in layout padding but after selection horizontal mode and choosing to show download speed first,download speed icon is always misaligned even after changing icon styles and position(left and right).

Details:
`Release Version:` 0.3.2
Operating System: Manjaro Linux
KDE Plasma Version: 5.26.5
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.1.19-1-MANJARO (64-bit)
Graphics Platform: Wayland

Screenshot:
![image](https://user-images.githubusercontent.com/75840152/227763092-88ce7e4d-2f75-45c5-87da-72c2c4d5c9f1.png)

**Comment by LeeVD** [comment]
Hello fynks
I believe the issue you have is/was due to a wider bug related to text alignment for the rows and the padding to move the upload and download rows closer together in 'vertical' layout mode.  I have just fix this issue and will be releasing a new version ASAP.
Thanks for feeding back the issue. Ta.
